### PR TITLE
#6 Fixed nested routing bug

### PR DESCRIPTION
**Pull request by Matzu89**
Added a simple conditional to check if the attribute name is properly set. If not, it gets set as expected. If it does, the renderer behaves like before.

### CODE REVIEW

**Comment by Matzu89** [comment]
Lol, something went wrong committing. Tabs are fixed

**Comment by TehShrike** [comment]
Huh, interesting.  Out of curiosity, what version of Riot were you using when this came up?

I'll try to test this and merge later today.  Can you give me an example of a template setup that would expose this issue?

**Comment by Matzu89** [comment]
Version 2.1.0
https://jsfiddle.net/Matzu89/oeb5kjnv/
Watch the console for current riot-tag value on ui-view

**Comment by TehShrike** [comment]
Awesome, thanks!  I'm hoping to actually get some open-source time tomorrow evening and get this released. :-)

**Comment by Matzu89** [comment]
Awesome, thanks!

**Comment by TehShrike** [comment]
Tested it out locally, looks legit to me.  Thanks!

**Comment by TehShrike** [comment]
Published in patch release 4.0.2.

**Pull request merged**
